[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
]

[tool.ruff]
line-length = 140
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = []

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["campaign_logger"]
forced-separate = ["test_campaign_logger"]
default-section = "third-party"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "basic"
