name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-20.04'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-20.04'
          - name: 'py27-cover (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'py27-cover (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-cover,codecov'
            os: 'windows-2019'
          - name: 'py27-cover (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-cover,codecov'
            os: 'macos-13'
          - name: 'py27-nocov (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-nocov'
            os: 'ubuntu-20.04'
          - name: 'py27-nocov (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-nocov'
            os: 'windows-2019'
          - name: 'py27-nocov (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-nocov'
            os: 'macos-13'
          - name: 'py36-cover (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'py36-cover (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            os: 'windows-2019'
          - name: 'py36-cover (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            os: 'macos-13'
          - name: 'py36-nocov (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            os: 'ubuntu-20.04'
          - name: 'py36-nocov (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            os: 'windows-2019'
          - name: 'py36-nocov (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            os: 'macos-13'
          - name: 'py37-cover (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'py37-cover (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            os: 'windows-2019'
          - name: 'py37-cover (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            os: 'macos-13'
          - name: 'py37-nocov (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            os: 'ubuntu-20.04'
          - name: 'py37-nocov (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            os: 'windows-2019'
          - name: 'py37-nocov (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            os: 'macos-13'
          - name: 'py38-cover (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'py38-cover (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            os: 'windows-2019'
          - name: 'py38-cover (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            os: 'macos-13'
          - name: 'py38-nocov (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            os: 'ubuntu-20.04'
          - name: 'py38-nocov (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            os: 'windows-2019'
          - name: 'py38-nocov (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            os: 'macos-13'
          - name: 'py39-cover (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'py39-cover (windows)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            os: 'windows-2019'
          - name: 'py39-cover (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            os: 'macos-13'
          - name: 'py39-nocov (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            os: 'ubuntu-20.04'
          - name: 'py39-nocov (windows)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            os: 'windows-2019'
          - name: 'py39-nocov (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            os: 'macos-13'
          - name: 'pypy27-cover (ubuntu)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'pypy27-cover (windows)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-cover,codecov'
            os: 'windows-2019'
          - name: 'pypy27-cover (macos)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-cover,codecov'
            os: 'macos-13'
          - name: 'pypy27-nocov (ubuntu)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-nocov'
            os: 'ubuntu-20.04'
          - name: 'pypy27-nocov (windows)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-nocov'
            os: 'windows-2019'
          - name: 'pypy27-nocov (macos)'
            python: 'pypy-2.7'
            toxpython: 'pypy27'
            python_arch: 'x64'
            tox_env: 'pypy27-nocov'
            os: 'macos-13'
          - name: 'pypy39-cover (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-cover,codecov'
            os: 'ubuntu-20.04'
          - name: 'pypy39-cover (windows)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-cover,codecov'
            os: 'windows-2019'
          - name: 'pypy39-cover (macos)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-cover,codecov'
            os: 'macos-13'
          - name: 'pypy39-nocov (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-nocov'
            os: 'ubuntu-20.04'
          - name: 'pypy39-nocov (windows)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-nocov'
            os: 'windows-2019'
          - name: 'pypy39-nocov (macos)'
            python: 'pypy-3.9'
            toxpython: 'pypy39'
            python_arch: 'x64'
            tox_env: 'pypy39-nocov'
            os: 'macos-13'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: install gettext
      if: runner.os == 'macOS'
      run: |
        brew install gettext
        brew link --force gettext
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
